var app={maxBufferPercentage:15,status:"starting",installed:!1,connected:!1,btapp:{},player:{videojs:{},projekktor:{}}};
(function(e){e.api||(e.api={});e=e.api;var g="udp://open.demonii.com:1337 udp://tracker.istole.it:80 http://tracker.yify-torrents.com/announce udp://tracker.publicbt.com:80 udp://tracker.openbittorrent.com:80 udp://tracker.coppersurfer.tk:6969 udp://exodus.desync.com:6969 http://exodus.desync.com:6969/announce".split(" "),b=function(c){if(!c.url)throw Error("No URL specified");var a=_.map(c.data,function(c,a){return a+"="+c}).join("&");0<_.size(c.data)&&(a="?"+a);a="http://query.yahooapis.com/v1/public/yql?q="+
encodeURIComponent("select * from jsonpost where url='"+encodeURI(c.url+a).replace(/[!,'()*]/g,"")+"' and postdata=''")+"&format=json&env="+encodeURIComponent("store://datatables.org/alltableswithkeys");return $.post(a,function(a){try{var b=a.query.results}catch(f){console.warn("Invalid JSON data returned");"function"===typeof c.error&&c.error("Invalid JSON data returned",a);"function"===typeof c.complete&&c.complete("Invalid JSON data returned",a);return}try{b=b.postresult}catch(d){console.warn("No data returned");
"function"===typeof c.error&&c.error("No data returned",a);"function"===typeof c.complete&&c.complete("No data returned",a);return}b?(b=b.replace(/<script[^>]*>[\s\S]*?<\/script>/gi,""),"function"===typeof c.success&&c.success(b),"function"===typeof c.complete&&c.complete(b)):(console.warn("No data returned"),"function"===typeof c.error&&c.error("No data returned",a),"function"===typeof c.complete&&c.complete("No data returned",a))}).fail(function(a){console.warn("Error connecting to "+c.url);"function"===
typeof c.error&&c.error("No data returned",a);"function"===typeof c.complete&&c.complete("No data returned",a)})},d=function(c){if(!c.url)throw Error("No URL specified");var a=_.map(c.data,function(c,a){return a+"="+c}).join("&");0<_.size(c.data)&&(a="?"+a);a="http://query.yahooapis.com/v1/public/yql?q="+encodeURIComponent("select content from data.headers where url='"+encodeURI(c.url+a).replace(/[!,'()*]/g,"")+"'")+"&format=json&env="+encodeURIComponent("store://datatables.org/alltableswithkeys");
return $.getJSON(a,function(a){try{var b=a.query.results}catch(f){console.warn("Invalid JSON data returned");"function"===typeof c.error&&c.error("Invalid JSON data returned",a);"function"===typeof c.complete&&c.complete("Invalid JSON data returned",a);return}try{b=b.resources.content.json}catch(d){console.warn("No data returned");"function"===typeof c.error&&c.error("No data returned",a);"function"===typeof c.complete&&c.complete("No data returned",a);return}b?("function"===typeof c.success&&c.success(b),
"function"===typeof c.complete&&c.complete(b)):(console.warn("No data returned"),"function"===typeof c.error&&c.error("No data returned",a),"function"===typeof c.complete&&c.complete("No data returned",a))}).fail(function(a){console.warn("Error connecting to "+c.url);"function"===typeof c.error&&c.error("No data returned",a);"function"===typeof c.complete&&c.complete("No data returned",a)})},n=function(c){var a={};a.imdbId=c.imdb_id;a.tmdbId=c.id;a.title=c.title||"";a.year=(c.release_date||"").split("-")[0];
a.description=c.overview||"";a.rating=c.vote_average||"";a.posterImage="";c.poster_path&&(a.posterImage="http://image.tmdb.org/t/p/w300"+c.poster_path);a.backdropImage="";c.backdrop_path&&(a.backdropImage="http://image.tmdb.org/t/p/w1280"+c.backdrop_path);a.runtime="";c.runtime&&(a.runtime=c.runtime+"m");a.cast=_.pluck(c.credits.cast.splice(0,3),"name");a.genres=_.pluck(c.genres,"name");0<c.trailers.youtube.length&&(a.trailer=c.trailers.youtube[0].source);a.similar=_.map(c.similar_movies.results,
function(c){return{tmdbId:c.id}});return a},p=function(c){return{name:"",quality:c.quality,seeds:c.seeds,peers:c.peers,size:c.size_bytes,url:"magnet:?xt=urn:btih:"+c.hash+"&tr="+g.join("&tr=")}},l=function(c){var a={};a.imdbId=c.external_ids.imdb_id;a.tmdbId=c.id;a.title=c.name||"";a.year=(c.first_air_date||"").split("-")[0];a.description=c.overview||"";a.rating=c.vote_average||"";a.posterImage="";c.poster_path&&(a.posterImage="http://image.tmdb.org/t/p/w300"+c.poster_path);a.backdropImage="";c.backdrop_path&&
(a.backdropImage="http://image.tmdb.org/t/p/w1280"+c.backdrop_path);a.runtime="";0<c.episode_run_time.length&&(a.runtime=c.episode_run_time[0]+"m");a.cast=_.pluck(c.credits.cast.splice(0,3),"name");a.genres=_.pluck(c.genres,"name");a.seasons=_.map(c.seasons,function(c){return{tmdbId:c.id,number:c.season_number,episodeCount:c.episode_count}});a.similar=_.map(c.similar.results,function(c){return{tmdbId:c.id}});return a},f=function(c){var a={};a.tmdbId=c.id;a.title=c.name||"";a.number=c.episode_number;
a.airDate=c.air_date||"";a.description=c.overview||"";a.stillImage="";c.still_path&&(a.stillImage="http://image.tmdb.org/t/p/w300"+c.still_path);return a},h=function(c){var a={};c=_.pick(c,"keywords","genre","sort","sortOrder","page");c.keywords&&(a.query_term=c.keywords);c.genre&&(a.genre=c.genre);c.sort&&(a.sort_by={popularity:"seeds",date:"year",rating:"rating"}[c.sort]);c.sortOrder&&(a.order_by=c.sortOrder);c.page&&(a.page=c.page);return a},k=function(c){var a={api_key:"f2d9fc51f6de779fb245cb121166eb5a"},
b;c=_.pick(c,"keywords","genre","sort","sortOrder","page");if("string"===typeof c.keywords&&0<c.keywords.length)b="search/tv",a.query=c.keywords;else{b="discover/tv";c.genre&&(a.with_genres={Action:28,Adventure:12,Animation:16,Comedy:35,Crime:80,Documentary:99,Drama:18,Family:10751,Fantasy:14,Foreign:10769,History:36,Horror:27,Music:10402,Mystery:9648,Romance:10749,"Science Fiction":878,"TV Movie":10770,Thriller:53,War:10752,Western:37,"Action & Adventure":10759,Education:10761,Kids:10762,News:10763,
Reality:10764,"Sci-Fi & Fantasy":10765,Soap:10766,Talk:10767,"War & Politics":10768}[c.genre]);c.sort&&(a.sort_by={popularity:"popularity",date:"first_air_date",rating:"vote_average"}[c.sort]+"."+(c.sortOrder||"desc"),"vote_average"!==a.sort_by.split(".")[0]||c.keywords&&0!==c.keywords.length||(a["vote_count.gte"]=15));var t=new Date,f=t.getUTCMonth()+1,f=10>f?"0"+f:f,d=t.getUTCDate(),d=10>d?"0"+d:d;a["first_air_date.lte"]=t.getUTCFullYear()+"-"+f+"-"+d}c.page&&(a.page=c.page);a.api=b;return a},s=
function(c,a,b,f){var d=$.ajax({url:"https://api.themoviedb.org/3/find/"+c,type:"GET",data:{external_source:"imdb_id",api_key:"f2d9fc51f6de779fb245cb121166eb5a"},error:function(){null!==app.queries.get(a)&&f&&f()},success:function(f){null!==app.queries.get(a)&&(0===f.movie_results.length&&0===f.tv_results.length?console.error("Couldn't find movie/show in TheMovieDatabase with the IMDB code",c):(0===f.movie_results.length&&b&&b(f.tv_results[0].id),0===f.tv_results.length&&b&&b(f.movie_results[0].id)))}});
app.queries.addToQuery(a,d)};e.movie={metadata:{single:function(c){if(c.tmdbId){c.queryId=c.queryId||0;var a=$.ajax({url:"https://api.themoviedb.org/3/movie/"+c.tmdbId,type:"GET",data:{append_to_response:"credits,trailers,similar_movies",api_key:"f2d9fc51f6de779fb245cb121166eb5a"},error:function(){null!==app.queries.get(c.queryId)&&c.error&&c.error(arguments)},success:function(a){null!==app.queries.get(c.queryId)&&c.success&&c.success(n(a))}});app.queries.addToQuery(c.queryId,a)}else c.imdbId||(console.error("Invalid API call: No ID provided"),
c.success&&c.success([])),s(c.imdbId,c.queryId,function(a){c.tmdbId=a;e.movie.metadata.single(c)},c.error)},multiple:function(){}},torrent:{single:function(c){c.ytsId||(console.error("Invalid API call: No ID provided"),c.success&&c.success(!1));c.queryId=c.queryId||0;var a=d({url:"https://yts.re/api/v2/movie_details.json?movie_id="+c.ytsId,error:function(){null!==app.queries.get(c.queryId)&&c.error&&c.error(arguments)},success:function(a){null!==app.queries.get(c.queryId)&&("error"===a.status?(console.error("https://yts.re/api/v2/: "+
a.status_message),c.success&&c.success(!1)):(a=a.data,a={imdbId:a.imdb_code||c.imdbId,tmdbId:c.tmdbId,ytsId:a.id,torrent:_.map(a.torrents,p)},c.success&&c.success(a)))}});app.queries.addToQuery(c.queryId,a)},multiple:function(c){var a=h(c.data);c.queryId=c.queryId||0;a=d({url:"https://yts.re/api/v2/list_movies.json",data:a,error:function(){null!==app.queries.get(c.queryId)&&c.error&&c.error(arguments)},success:function(a){if(null!==app.queries.get(c.queryId))if("error"===a.status)console.error("https://yts.re/api/v2/: "+
a.status_message),c.success&&c.success([]);else if(a.data.hasOwnProperty("movies")){a=a.data.movies;_.isArray(a)||(a=[a]);var b=[];_.each(a,function(a){a.hasOwnProperty("imdb_code")&&b.push({imdbId:a.imdb_code,ytsId:a.id,torrent:_.map(a.torrents,p)})});c.success&&c.success(b)}else c.success&&c.success([])}});app.queries.addToQuery(c.queryId,a)},similar:function(c){c.ytsId||(console.error("Invalid API call: No ID provided"),c.success&&c.success(!1));c.queryId=c.queryId||0;var a=d({url:"https://yts.re/api/v2/movie_suggestions.json?movie_id="+
c.ytsId,error:function(){null!==app.queries.get(c.queryId)&&c.error&&c.error(arguments)},success:function(a){if(null!==app.queries.get(c.queryId))if("error"===a.status)console.error("https://yts.re/api/v2/: "+a.status_message),c.success&&c.success([]);else{a=a.data.movie_suggestions;_.isArray(a)||(a=[a]);var b=[];_.each(a,function(a){b.push({imdbId:a.imdb_code,ytsId:a.id,torrent:_.map(a.torrents,p)})});c.success&&c.success(b)}}});app.queries.addToQuery(c.queryId,a)}}};e.tvShow={metadata:{single:function(c){if(c.tmdbId){var a=
$.ajax({url:"https://api.themoviedb.org/3/tv/"+c.tmdbId,type:"GET",data:{append_to_response:"credits,external_ids,similar",api_key:"f2d9fc51f6de779fb245cb121166eb5a"},error:function(){null!==app.queries.get(c.queryId)&&c.error&&c.error(arguments)},success:function(a){null!==app.queries.get(c.queryId)&&c.success&&c.success(l(a))}});app.queries.addToQuery(c.queryId||0,a)}else c.imdbId||(console.error("Invalid API call: No ID provided"),c.success&&c.success([])),s(c.imdbId,c.queryId,function(a){c.tmdbId=
a;e.tvShow.metadata.single(c)},c.error)},season:function(c){if(c.tmdbId){var a=$.ajax({url:"https://api.themoviedb.org/3/tv/"+c.tmdbId+"/season/"+c.seasonNumber,type:"GET",data:{api_key:"f2d9fc51f6de779fb245cb121166eb5a"},error:function(){null!==app.queries.get(c.queryId)&&c.error&&c.error(arguments)},success:function(a){null!==app.queries.get(c.queryId)&&(a=_.map(a.episodes,f),c.success&&c.success(a))}});app.queries.addToQuery(c.queryId||0,a)}else c.imdbId||(console.error("Invalid API call: No ID provided"),
c.success&&c.success([])),s(c.imdbId,c.queryId,function(a){c.tmdbId=a;e.tvShow.metadata.season(c)},c.error)},multiple:function(c){var a=k(c.data),b=a.api;delete a.api;a=$.ajax({url:"https://api.themoviedb.org/3/"+b,type:"GET",data:a,error:function(){null!==app.queries.get(c.queryId)&&c.error&&c.error(arguments)},success:function(a){null!==app.queries.get(c.queryId)&&(a=_.chain(a.results).reject(function(a){return!a.name}).reject(function(a){return!a.poster_path}).map(function(a){return{tmdbId:a.id}}).value(),
c.success&&c.success(a))}});app.queries.addToQuery(c.queryId||0,a)}},torrent:{single:function(c){var a=(10>c.episode?"0":"")+c.episode,f=(10>c.season?"0":"")+c.season,d=c.title+" S"+f+"E"+a,e=function(b){b=$(b).find("a.imagnet");for(var d=[],m=0;m<b.length;m++){var q;q=$(b.get(m));var e=$(q.parents("tr").get(0)).find("td");q={name:e.find(".torrentname .cellMainLink").text()||"",quality:"",seeds:$(e.get(-2)).html()||0,peers:$(e.get(-1)).html()||0,size:$(e.get(-5)).html()||"",url:q.attr("href")||""};
0!=q.seeds&&(e=q.name.toLowerCase(),-1===e.indexOf("s"+f+"e"+a)&&-1===e.indexOf(c.season+"x"+c.episode)&&-1===e.indexOf(c.season+"x"+a)||d.push(q))}return d},h={url:"http://kickass.to/usearch/"+d+"/",error:function(){null!==app.queries.get(c.queryId)&&c.error&&c.error()},success:function(f){null!==app.queries.get(c.queryId)&&(f=e(f),0===f.length?(d=c.title+" "+c.season+"x"+a,h.url="http://kickass.to/usearch/"+d+"/",h.success=function(a){null!==app.queries.get(c.queryId)&&(a=e(a),c.success&&c.success(a))},
f=b(h),app.queries.addToQuery(c.queryId||0,f)):c.success&&c.success(f))}},l=b(h);app.queries.addToQuery(c.queryId||0,l)},season:function(){},multiple:function(){}}};e.all={search:function(c){var a=k(c);delete a.api;a=$.ajax({url:"https://api.themoviedb.org/3/search/multi",type:"GET",data:a,error:function(){null!==app.queries.get(c.queryId)&&c.error&&c.error(arguments)},success:function(a){null!==app.queries.get(c.queryId)&&(a=_.chain(a.results).reject(function(a){return!a.title&&!a.name}).reject(function(a){return!a.first_air_date&&
!a.release_date}).reject(function(a){return!a.poster_path}).reject(function(a){return 15>a.vote_count}).map(function(a){return{tmdbId:a.id,title:a.title||a.name,type:a.media_type,year:(a.first_air_date||a.release_date).slice(0,4),posterImage:"http://image.tmdb.org/t/p/w300"+a.poster_path}}).value(),c.success&&c.success(a))}});app.queries.addToQuery(c.queryId||0,a)}}})(window.app);
(function(e){e.fn||(e.fn={});e=e.fn;e.closeDetails=function(){var e=$("#movie-details, #tv-details").filter(":visible");app.nav.switchView(e.data("previous-view"));e.data("previous-view",null);_.each(e.find("*"),function(b){b=$(b);b.data("query-ids")&&app.queries.cancel(b)});e.animate({width:"hide"}).find("#movie-details-foreground, #tv-details-foreground").fadeOut();$("#tv-details-episodes").slideUp();$("#tv-details-desc").slideDown();document.title="webflix.me"};e.connectToTorque=function(){app.btapp=
new Btapp;app.btapp.connect({product:"Torque"});app.setup.torqueMessageReciever();app.btapp.on("client:connected",function(){$("#setup-modal").is(":visible")&&$("#setup-modal, #modal-bg").fadeOut();$("#first-run").val("0").trigger("change");app.torrents.updateAll()});app.btapp.live("settings default_download_directory",function(e,b){var d=$("#default-download-directory");""==d.val()&&d.val(e).trigger("change")});app.btapp.live("settings max_dl_rate",function(e,b){var d=$("#max-download-speed");"0"==
d.val()&&d.val(e).trigger("change")});app.btapp.live("settings max_ul_rate",function(e,b){var d=$("#max-upload-speed");"0"==d.val()&&d.val(e).trigger("change")})};e.openModal=function(e){var b=$("#modal-bg");b.is(":visible")&&b.click();b.data("previous-view",app.nav.currentView());b.attr("data-modal",e);$(e+", #modal-bg").fadeIn()};e.status=function(e,b,d){"string"===typeof b?($("#status-progress").show().find(".bar").css("width",b),$("#status-loading-indicator").hide()):($("#status-progress").hide(),
$("#status-loading-indicator").show());if(d)$("#status-cancel").show().on("click",d);else $("#status-cancel").hide().unbind("click");!1===e?$("#status").fadeOut():$("#status").fadeIn().find("#status-text").html(e)}})(window);
(function(e){var g={},b=["movie","tvShow"],d={movie:function(b){return{imdbId:b.imdbId,tmdbId:b.tmdbId,ytsId:b.ytsId}},tvShow:function(b){return{imdbId:b.imdbId,tmdbId:b.tmdbId}}},n=function(d,f){var h=e.lists.get(d);if("object"!==typeof h)return[];"undefined"===typeof h[f]&&b.indexOf(f)&&(h[f]=[]);return h[f]||[]},p=function(b,f,d){"object"===typeof e.lists.get(b)&&(g[b][f]=d)};e.lists={newList:function(d,f){f=f||{};g[d]={};_.each(b,function(b){g[d][b]=[];_.isArray(f[b])&&_.each(f[b],function(f){e.lists.addToList(d,
b,f)})});e.lists.save()},addToList:function(b,f,h){e.lists.removeFromList(b,f,h);"object"!==typeof e.lists.get(b)&&e.lists.newList(b);var k=n(b,f);h=(d[f]||_.identity)(h);h.time=_.now();k.push(h);g[b][f]=k;p(b,f,k);e.lists.save()},removeFromList:function(b,f,d){var k=e.lists.search(b,f,d);d=n(b,f);d=_.reject(d,function(b){return _.findWhere(k,b)});p(b,f,d);e.lists.save()},search:function(b,f,e){b=n(b,f);var k=(d[f]||_.identity)(e);return _.filter(b,function(b){return _.matches(k)(b)||_.matches(b)(k)})},
get:function(b){e.lists.load();return g[b]},save:function(){$.jStorage.set("lists",g)},load:function(){g=$.jStorage.get("lists",{})},renderList:function(b,f,d){var k=e.lists.get(b)||{};d=d||{};_.each(f,function(b,c){app.media[c].byId({container:b,failMessage:d[c],items:k[c]||[]})})}}})(window.app);
(function(e){e.media||(e.media={});e=e.media;var g=function(a,c,b){if("undefined"===typeof c||1===c)a.empty(),app.queries.cancel(a);c=app.queries.newQuery();app.queries.associateQuery(c,a);a.data("next-page",b);a.addClass("loading");$(a.data("loading-indicator")).show();return c},b=function(a){a=_.defaults(a||{},{container:$("#results")});a.filter=_.defaults(a.filter||{},{sort:"popularity",sortOrder:"desc",page:1});return a},d=function(a,c,b,d){a.removeClass("loading");$(a.data("loading-indicator")).fadeOut();
a.data("next-page","");1===b&&(c&&0<c.length?a.html("<div class='no-results'>No "+d+"s matching <span class='keywords'>"+c+"</span> were found.</div>"):a.html("<div class='no-results'>No "+d+" results found.</div>"))},n=function(a,c){a.removeClass("loading");$(a.data("loading-indicator")).fadeOut();a.html("<div class='no-results'>"+c+"</div>")},p=function(a,c,b){3>c?setTimeout(function(){a(c+1)},3E3):b()},l=function(a){a=Math.round(a)/2;for(var c="",b=1;b<=Math.floor(a);b++)c+="<i class='icon-star'></i>";
0<a%1&&(c+="<i class='icon-star-half-empty'></i>");for(b=Math.ceil(a);5>b;b++)c+="<i class='icon-star-o'></i>";return c},f=function(a,c,b){var d=a.metadata,f=0<app.lists.search("bookmarks",c,a).length,h=$("<div data-imdb-id='"+d.imdbId+"' class='media-result navigable-item'></div>");h.append($("<div class='result-container'></div>").append("<div class='result-poster-container'><img src='"+d.posterImage+"'></div>").append($("<div class='clearfix result-info' title='"+d.title+"'></div>").append("<div class='result-title'>"+
d.title+"</div>").append("<a class='result-bookmark"+(f?" bookmarked":"")+"'><i class='icon-heart'></i></a>").append("<div class='result-year'>"+d.year+"</div>").append("<div class='result-rating simptip-position-top simptip-fade simptip-smooth' data-tooltip='"+d.rating+"'>"+l(d.rating)+"</div>")));h.on("click",function(){e[c].openDetails(a)});h.on("mousemove",function(){app.nav.paused()||app.nav.selectElement(h)}).on("mouseout",function(){app.nav.paused()||app.nav.deselect()}).find(".result-bookmark").on("click",
function(b){b.preventDefault();b.stopPropagation();f?(app.lists.removeFromList("bookmarks",c,a),$(this).removeClass("bookmarked")):(app.lists.addToList("bookmarks",c,a),$(this).addClass("bookmarked"));return!1});d.rating||h.find(".result-rating").hide();b.append(h.hide());h.find("img").on("load",function(){h.detach();b.append(h.fadeIn().css("display",""))})},h=function(a,c){var b=c.metadata;a.find(".media-details-poster").find("img").attr("src",null).attr("src",b.posterImage);a.find(".media-details-backdrop").find("img").attr("src",
null).attr("src",b.backdropImage);a.find(".media-details-title").html(b.title+" <span>("+b.year+")</span>");a.find(".media-details-desc").html(b.description);a.find(".media-details-actors").html(b.cast.join(", "));a.find(".media-details-runtime").html(b.runtime);b.rating?a.find(".media-details-rating").attr("data-tooltip",b.rating).html(l(b.rating)).show():a.find(".media-details-rating").attr("data-tooltip","").html("").hide();a.is(":visible")&&a.hide();a.find(".media-details-foreground").hide();
a.animate({width:"show"}).find(".media-details-foreground").fadeIn(400,app.nav.deselect);a.data("previous-view")||a.data("previous-view",app.nav.currentView())},k=function(a,c,b){var d=b.number+1,f=c.number;d>c.episodeCount&&(d=1,f=c.number+1);f<a.metadata.seasons.length&&d<a.metadata.seasons[f].episodeCount&&app.api.tvShow.torrent.single({title:a.metadata.title,season:f,episode:d,queryId:0,success:function(c){var b=c[0];app.api.tvShow.metadata.season({tmdbId:a.tmdbId,seasonNumber:f,queryId:0,success:function(c){var m=
$("#player"),e=m.data("on-ended");m.data("next-hash",b.url);m.data("on-ended",function(){e&&e();$("#modal-bg").click();var m=_.findWhere(c,{number:d});$("#next-episode-intro-title").html("Playing next episode in 10 seconds...");var h=$("#next-episode-still").hide().attr("src",null);m.stillImage&&h.show().attr("src",m.stillImage);$("#next-episode-air-date").html(m.airDate);$("#next-episode-title").html("Season "+f+" Episode "+m.number+": "+m.title);$("#next-episode-description").html(m.description||
a.metadata.description);$("#next-episode-torrent-link").html(b.url).attr("title",b.url);var h=$("#next-episode-torrent-quality"),r=b.seeds+(1==b.seeds?" seed":" seeds")+" - "+b.peers+(1==b.peers?" peer":" peers");h.attr("title",r).attr("data-tooltip",r);10>b.seeds?h.css("color","red"):100>b.seeds?h.css("color","orange"):h.css("color","lime");$("#next-episode-intro").fadeIn();var z=(new Date).getTime(),t=!1,n;(function B(){var c=10-((new Date).getTime()-z)/1E3;$("#next-episode-intro-title").html("Playing next episode in "+
Math.round(c)+" seconds...");$("#next-episode-cancel-btn").unbind("click").on("click",function(){t=!0;clearTimeout(n);$("#next-episode-intro").fadeOut()});0>=c?($("#next-episode-intro").fadeOut(),app.torrents.play(b.url,a),$("#autoplay-next-episode").is(":checked")&&k(a,a.metadata.seasons[f],m)):t||(n=setTimeout(B,1E3))})()})}})}})},s=e.movie={},c=e.tvShow={};s.list=function(a){a=b(a);var c=g(a.container,a.filter.page,function(){a.filter.page++;s.list(a)});1===a.filter.page&&a.container.empty();var e=
_.partial(d,a.container,a.filter.keywords,a.filter.page,"movie");(function v(b){var d=_.partial(p,v,b,function(){e();var c=$("<a style='padding-right: 20px' title='Try again'><i class='icon-repeat'></i></a>").on("click",function(){s.list(a)});a.container.find(".no-results").empty().append(c).append("Error getting movies...")});app.api.movie.torrent.multiple({data:a.filter,queryId:c,success:function(b){if(null!==app.queries.get(c)){0===_.size(b)&&e();var m=0;_.each(b,function(q){app.api.movie.metadata.single(_.extend({},
q,{queryId:c,success:function(d){if(null!==app.queries.get(c))if(a.filter.genre&&-1===d.genres.indexOf(a.filter.genre))++m===_.size(b)&&e();else{a.container.removeClass("loading");$(a.container.data("loading-indicator")).fadeOut();q.metadata=d;q.tmdbId=d.tmdbId;q.imdbId=d.imdbId;try{f(q,"movie",a.container)}catch(h){++m===_.size(b)&&e()}}},error:d}))})}},error:d})})(1)};c.list=function(a){a=b(a);var e=g(a.container,a.filter.page,function(){a.filter.page++;c.list(a)});1===a.filter.page&&a.container.empty();
var h=_.partial(d,a.container,a.filter.keywords,a.filter.page,"TV show");(function v(b){var d=_.partial(p,v,b,function(){h();var b=$("<a style='padding-right: 20px' title='Try again'><i class='icon-repeat'></i></a>").on("click",function(){c.list(a)});a.container.find(".no-results").empty().append(b).append("Error getting TV shows...")});app.api.tvShow.metadata.multiple({data:a.filter,queryId:e,success:function(c){if(null!==app.queries.get(e)){0===_.size(c)&&h();var b=0;_.each(c,function(q){app.api.tvShow.metadata.single(_.extend({},
q,{queryId:e,success:function(d){if(null!==app.queries.get(e))if(a.filter.genre&&-1===d.genres.indexOf(a.filter.genre))++b===_.size(c)&&h();else{a.container.removeClass("loading");$(a.container.data("loading-indicator")).fadeOut();q.metadata=d;q.imdbId=d.imdbId;try{f(q,"tvShow",a.container)}catch(k){++b===_.size(c)&&h()}}},error:d}))})}},error:d})})(1)};s.byId=function(a){a=_.defaults(a||{},{container:$("#results"),render:f});var c=g(a.container),b=_.partial(n,a.container,a.failMessage||"There aren't any movies in this list yet.");
0===_.size(a.items)&&b();var d=0;_.each(a.items,function(f){(function x(e){var m=_.partial(p,x,e,function(){if(++d===_.size(a.items)){b();var c=$("<a style='padding-right: 20px' title='Try again'><i class='icon-repeat'></i></a>").on("click",function(){s.byId(a)});a.container.find(".no-results").empty().append(c).append("Error getting movies...")}});app.api.movie.torrent.single(_.extend({},f,{queryId:c,success:function(b){null!==app.queries.get(c)&&(!1===b?m():app.api.movie.metadata.single(_.extend({},
b,{queryId:c,success:function(d){if(null!==app.queries.get(c)){a.container.removeClass("loading");$(a.container.data("loading-indicator")).fadeOut();b.metadata=d;b.tmdbId=d.tmdbId;b.imdbId=d.imdbId;try{a.render(b,"movie",a.container)}catch(f){m()}}},error:m})))},error:m}))})(1)})};c.byId=function(a){a=_.defaults(a||{},{container:$("#results"),render:f});var b=g(a.container),d=_.partial(n,a.container,a.failMessage||"There aren't any TV shows in this list yet.");0===_.size(a.items)&&d();var e=0;_.each(a.items,
function(f){(function x(h){var m=_.partial(p,x,h,function(){if(++e===_.size(a.items)){d();var b=$("<a style='padding-right: 20px' title='Try again'><i class='icon-repeat'></i></a>").on("click",function(){c.byId(a)});a.container.find(".no-results").empty().append(b).append("Error getting TV shows...")}});app.api.tvShow.metadata.single(_.extend({},f,{queryId:b,success:function(c){if(null!==app.queries.get(b))if(!1===f)m();else{a.container.removeClass("loading");$(a.container.data("loading-indicator")).fadeOut();
f.metadata=c;f.tmdbId=c.tmdbId;f.imdbId=c.imdbId;try{a.render(f,"tvShow",a.container)}catch(d){m()}}},error:m}))})(1)})};s.openDetails=function(a){var c=$("#movie-details"),b=a.metadata,d=a.torrent;h(c,a);if(b.trailer)$("#movie-details-trailer").show().unbind("click").on("click",function(){$("#youtube-player").attr("src","http://www.youtube.com/embed/"+b.trailer+"?autoplay=1&origin=http://webflix.me");$("#youtube-modal").data("onClose",function(){$("#youtube-player").attr("src",null)});fn.openModal("#youtube-modal")});
else $("#movie-details-trailer").hide().unbind("click");var f=$("#movie-details-similar").empty();app.api.movie.torrent.similar({ytsId:a.ytsId,success:function(a){a=_.shuffle(a).slice(0,3);s.byId({container:f,items:a,failMessage:"Couldn't load similar movies...",render:function(a,c,b){$(f.removeClass("loading").data("loading-indicator")).hide();var d=$("<a>"+a.metadata.title+"</a>").hide();d.on("click",function(){e[c].openDetails(a)});b.is(":empty")?b.html("People also watched: ").append(d.fadeIn().css("display",
"")).fadeIn():b.append(", ").append(d.fadeIn().css("display",""))}})},error:function(){f.empty().hide()}});var k=_.indexBy(d,"quality");k.hasOwnProperty("1080p")&&k.hasOwnProperty("720p")?$("#movie-details-quality").show():$("#movie-details-quality").hide();if(0===d.length)$("#movie-details-watch").hide();else $("#movie-details-watch").show().unbind("click").on("click",function(){var c;c=$("#movie-details-quality");c=c.is(":hidden")?d[0]:c.find("input[type=checkbox]").is(":checked")?k["1080p"]:k["720p"];
a.mediaType="movie";app.torrents.play(c.url,a)});app.nav.switchView("movie-details")};c.openDetails=function(a){var b=$("#tv-details"),d=a.metadata;h(b,a);var f=$("#tv-details-similar").empty();0<d.similar.length?c.byId({container:f,items:d.similar.slice(0,3),failMessage:"Couldn't load similar shows...",render:function(a,c,b){$(f.removeClass("loading").data("loading-indicator")).hide();var d=$("<a>"+a.metadata.title+"</a>").hide();d.on("click",function(){e[c].openDetails(a)});b.is(":empty")?b.html("People also watched: ").append(d.fadeIn().css("display",
"")).fadeIn():b.append(", ").append(d.fadeIn().css("display",""))}}):f.empty().hide();$("#tv-details-seasons, #tv-details-episodes").empty();$("#tv-details-episode-title, #tv-details-episode-desc, #tv-details-episode-air-date").html("");$("#tv-details-episode-still").find("img").attr("src",null);$("#tv-details-episode-title, #tv-details-episode").hide();var k=$("<li class='tv-details-season navigable-item'></li>"),n=$("#tv-details-seasons").empty();_.each(d.seasons,function(b){0!==b.number&&"number"===
typeof b.number&&n.append(k.clone().data("season-number",b.number).html("Season "+b.number).on("mousemove",function(){app.nav.paused()||app.nav.selectElement($(this))}).on("mouseout",function(){app.nav.paused()||app.nav.deselect()}).on("click",function(){c.openSeason(a,b)}))});n.scrollTo(0).find(".tv-details-season").first().click();app.nav.switchView("tv-details")};c.openSeason=function(a,b){var d=$("#tv-details-episodes");$(".tv-details-season").removeClass("active").filter(function(){return $(this).data("season-number")===
b.number}).addClass("active");var f=g(d);d.slideUp(300,function(){app.api.tvShow.metadata.season({tmdbId:a.tmdbId,imdbId:a.imdbId,queryId:f,seasonNumber:b.number,success:function(e){if(null!==app.queries.get(f)){d.empty();var h=$("<li class='tv-details-episode navigable-item'></li>");_.each(e,function(f){d.append(h.clone().data("episode-number",f.number).attr("title",f.title).html("<span>"+f.number+"</span> "+f.title).on("mousemove",function(){app.nav.paused()||app.nav.selectElement($(this))}).on("mouseout",
function(){app.nav.paused()||app.nav.deselect()}).on("click",function(){c.openEpisode(a,b,f)}))});d.removeClass("loading");$(d.data("loading-indicator")).fadeOut();d.slideDown(300,function(){d.scrollTo(0).parent()});d.hasClass("used-keyboard")&&(app.nav.selectElement($(".tv-details-episode").first()),d.scrollTo(".selected").removeClass("used-keyboard"))}},error:function(){d.removeClass("loading");$(d.data("loading-indicator")).fadeOut()}})})};c.openEpisode=function(a,c,b){var d=$("#tv-details-episode-container"),
f=$("#tv-show-torrent-links");$(".tv-details-episode").removeClass("active").filter(function(){return $(this).data("episode-number")===b.number}).addClass("active");b.stillImage?$("#tv-details-episode-still").find("img").attr("src",null).attr("src",b.stillImage).parent().show():$("#tv-details-episode-still").find("img").attr("src",null).parent().hide();$("#tv-details-episode-title").html(b.title).attr("title",b.title);$("#tv-details-episode-air-date").html("Air date: "+b.airDate);$("#tv-details-episode-desc").html(b.description||
a.description);$("#tv-details-episode-title, #tv-details-episode").fadeIn();var e=g(d,2);d.removeClass("no-links").addClass("loading").fadeIn();f.empty();(function w(m){m=_.partial(p,w,m,function(){d.removeClass("loading");d.addClass("no-links")});app.api.tvShow.torrent.single({title:a.metadata.title,season:c.number,episode:b.number,queryId:e,success:function(m){if(null!==app.queries.get(e)){var h=$("#tv-show-torrent-link-template").clone().attr("id","");_.each(m,function(d,e){var m=h.clone();m.find(".link-name").html("Link "+
(e+1));m.find(".link-detailed").attr("title",d.name.replace(/['"]/g,"")).html("<strong>"+d.size+"</strong> &middot; "+d.name);m.find(".link-info-detailed").html(d.seeds+(1==d.seeds?" seed":" seeds")+" &middot; "+d.peers+(1==d.peers?" peer":" peers"));10>d.seeds?m.find(".link-info").addClass("low"):100>d.seeds?m.find(".link-info").addClass("med"):m.find(".link-info").addClass("high");m.on("mousemove",function(){app.nav.paused()||app.nav.selectElement($(this))}).on("mouseout",function(){app.nav.paused()||
app.nav.deselect()}).on("click",function(){$("#modal-bg").click();a.mediaType="tvShow";app.torrents.play(d.url,a);$("#autoplay-next-episode").is(":checked")&&k(a,c,b)});f.append(m);3>=f.children().length&&m.show()});d.removeClass("loading");if(0===f.children().length)d.addClass("no-links");else if(3<f.children().length){$("#tv-details-episode-torrents-more").remove();var n=$("<div class='link navigable-item' id='tv-details-episode-torrents-more' style='text-align: center'>View more<div class='link-detailed'><i class='icon-chevron-down'></i></div></div>");
n.on("mousemove",function(){app.nav.paused()||app.nav.selectElement($(this))}).on("mouseout",function(){app.nav.paused()||app.nav.deselect()}).on("click",function(){var a=f.children();$(a.filter(":hidden").slice(0,3)).slideDown(100,"swing",function(){0===a.filter(":hidden").length&&n.slideUp()})});f.append(n)}}},error:m})})(1)}})(window.app);
(function(e){e.nav||(e.nav={});e=e.nav;var g={};e.View=function(b,d,e){this.name=b;this.panes=d;this.defaultPane="undefined"!==typeof e?e:1;g[b]=this};var b="results",d=1;e.currentView=function(){return b};e.switchView=function(f){"undefined"===typeof f&&(f=b);g[f]&&(b=f,d=g[f].defaultPane)};var n=function(b){var d=b.find(".navigable-item:visible").not(".active");if(0===d.length)return 0;b.hide();var e=d.css("width");b.show();var n=_.reduce(d,function(a,c){return a+$(c).outerWidth()},0)/d.length,
c=parseFloat(d.css("min-width"))||0,d=parseFloat(d.css("max-width"))||Infinity;return-1!==e.indexOf("%")&&n>c&&n<d?Math.floor(100/+e.split("%")[0]):Math.floor(b[0].clientWidth/n)},p=function(f,h){if(!e.paused()){var k=g[b],l=k.panes[d],c=n(l),l=l.find(".navigable-item:visible").not(".active"),a=l.filter(".selected"),a=l.index(a);-1===a&&(a=-f-h*c);0===h&&0<f&&a===l.length-1&&d<k.panes.length-1||0===h&&0<f&&a%c===c-1&&d<k.panes.length-1||0===h&&0>f&&0===a%c&&0<d?k.panes[d+f].is(":hidden")||(d+=f,l.removeClass("selected"),
p(0,0)):(e.pause(),a+f+h*c>=l.length||0>a+f+h*c?e.unpause():(e.select(d,a+f+h*c),a=$(l.get(a+f+h*c)),a.parent().scrollTo(a,{axis:"y",duration:100,onAfter:function(){e.unpause()}})))}};e.right=function(){p(1,0)};e.left=function(){p(-1,0)};e.up=function(){p(0,-1)};e.down=function(){p(0,1)};e.select=function(f,h){var n=$(g[b].panes[f].find(".navigable-item:visible").not(".active").get(h));e.deselect();n.addClass("selected");d=f};e.selectElement=function(b){if(!b.hasClass("active")){var d=b.parents(".navigable-pane");
b=d.find(".navigable-item:visible").not(".active").index(b);d=d.data("pane-number");e.select(d,b)}};e.deselect=function(){$(".navigable-item.selected").removeClass("selected")};var l=!1;e.pause=function(){l=!0};e.unpause=function(){setTimeout(function(){l=!1},100)};e.paused=function(){return l}})(window.app);
(function(e){var g=[[]];e.queries={associateQuery:function(b,d){"undefined"===typeof d.data("query-ids")&&d.data("query-ids",[]);d.data("query-ids").push(b)},newQuery:function(b){_.isArray(b)||(b=[]);var d=g.length;g[d]=b;return d},addToQuery:function(b,d){_.isNull(g[b])?d.abort():(_.isArray(g[b])||(g[b]=[]),g[b].push(d))},get:function(b){return g[b]},cancel:function(b){b instanceof jQuery&&b.data("query-ids")?(_.each(b.data("query-ids"),function(b){app.queries.cancel(b)}),b.data("query-ids",[])):
_.isArray(g[b])&&(_.each(g[b],function(b){b.abort()}),g[b]=null)}}})(window.app);
(function(e){e.setup||(e.setup={});e=e.setup;var g=function(b){$(".results-page").each(function(){$($(this).data("loading-indicator")).fadeOut();_.each($(this).data("query-ids"),function(b){app.queries.cancel(b)})}).empty();$(".main").hide();fn.closeDetails();"sidebar-downloads"!==b.attr("id")&&clearInterval($("#downloads").fadeOut().data("update-interval"));$("#search-overlay").is(":visible")&&$("#search-overlay-bg").click();$("#sidebar").find("a").removeClass("active");b.addClass("active")};e.errorTracking=
function(){if("undefined"!==typeof ga){var b=function(b,e,g,l,f){"undefined"!==typeof g&&(e+=" ("+g,"undefined"!==typeof l&&(e+=":"+l,"undefined"!==typeof f&&(e+=","+f)),e+=")");ga("send","event","error",b,e)};window.onerror=function(d,e,g,l){e&&(e=e.split("/"),e=e[e.length-1]);b("js error",d,e,g,l)};$(document).ajaxError(function(d,e,g){b("ajax error",d.result||e.statusText,g.url)})}};e.keyboardShortcuts=function(){Mousetrap.reset();$("#keyboard-shortcuts").is(":checked")&&(Mousetrap.bind("?",function(){fn.openModal("#info-modal")}),
Mousetrap.bind("q",function(){$("#sidebar-search").click()}),Mousetrap.bind("f",function(){$("#videojs-container").is(":visible")&&(app.player.videojs.isFullscreen()?app.player.videojs.exitFullscreen():app.player.videojs.requestFullscreen());$("#projekktor-container").is(":visible")&&(app.player.projekktor.getInFullscreen()?app.player.projekktor.setFullscreen(!1):app.player.projekktor.setFullscreen(!0))}),Mousetrap.bind(["esc","backspace"],function(b){b&&b.preventDefault&&b.preventDefault();b=$("#modal-bg");
if(b.is(":visible"))return b.click(),!1;$(".media-details").is(":visible")&&fn.closeDetails();return!1}),Mousetrap.bind(["space","p"],function(){$("#videojs-container").is(":visible")&&(app.player.videojs.paused()?app.player.videojs.play():app.player.videojs.pause());$("#projekktor-container").is(":visible")&&app.player.projekktor.setPlayPause()}),Mousetrap.bind("up",function(b){b&&b.preventDefault&&b.preventDefault();if($("#videojs-container").is(":visible"))return app.player.videojs.volume(Math.min(app.player.videojs.volume()+
0.05,1)),!1;if($("#projekktor-container").is(":visible"))return app.player.projekktor.setVolume(Math.min(app.player.projekktor.getVolume()+0.05,1)),!1;app.nav.up();return!1}),Mousetrap.bind("down",function(b){b&&b.preventDefault&&b.preventDefault();if($("#videojs-container").is(":visible"))return app.player.videojs.volume(Math.max(app.player.videojs.volume()-0.05,0)),!1;if($("#projekktor-container").is(":visible"))return app.player.projekktor.setVolume(Math.max(app.player.projekktor.getVolume()-0.05,
0.05)),!1;app.nav.down();return!1}),Mousetrap.bind("left",function(b){b&&b.preventDefault&&b.preventDefault();if($("#videojs-container").is(":visible"))return app.player.videojs.currentTime(app.player.videojs.currentTime()-10),!1;app.nav.left();return!1}),Mousetrap.bind("right",function(b){b&&b.preventDefault&&b.preventDefault();if($("#videojs-container").is(":visible"))return app.player.videojs.currentTime(app.player.videojs.currentTime()+10),!1;app.nav.right();return!1}),Mousetrap.bind("enter",
function(){$(".navigable-item.selected:not(.active):visible").click().removeClass("selected")}),$("#sidebar, #movie-details").on("mouseover",function(){$(this).find(".selected").removeClass("selected")}))};e.loadNewPage=function(){$(".results-page").scroll(function(){var b=$(this);b.hasClass("loading")||b.scrollTop()+b.height()<b[0].scrollHeight-500||"function"===typeof b.data("next-page")&&b.data("next-page")()})};e.modals=function(){$("#modal-bg").on("click",function(){$(".modal, #modal-bg, #status").fadeOut();
var b=$($(this).attr("data-modal"));$(this).attr("data-modal","");$(this).data("previous-view")&&app.nav.switchView($(this).data("previous-view"));$(this).data("previous-view",null);b.fadeOut();b.data("on-close")&&b.data("on-close")(b);"tos-modal"!==b.attr("id")||app.connected||setTimeout(function(){fn.openModal("#setup-modal")},500)})};e.search=function(){var b=function(){var b=$("#search-overlay");$("#search-overlay-container").animate({width:0});b.fadeOut(400,function(){$("#search-overlay-keywords").val("");
$("#search-overlay-results").html("")});app.nav.switchView(b.data("previous-view"))};$("#search-overlay-bg").on("click",b);$("#search-overlay-form").on("submit",function(b){b&&b.preventDefault&&b.preventDefault();g($("#sidebar-search"));app.nav.switchView("search");$("#search-genre, #search-sort").attr("selectedIndex",0);$("#search-results").fadeIn();b=$("#search-overlay-keywords");$("#keywords").val(b.val());$("#search-bar").submit();b.val("");return!1});$("#search-overlay-keywords").on("keyup",
_.debounce(function(b){if(40!==b.keyCode&&38!==b.keyCode){var e=$(this).val(),g=$("#search-overlay-results");if(""===e)g.html("");else if(g.data("search-keywords")!==e){var l=$("#search-overlay-result").clone().attr("id","");app.api.all.search({keywords:e,queryId:0,success:function(b){g.empty().data("search-keywords",e);_.each(b,function(b){var d=l.clone();d.find(".search-overlay-result-poster").find("img").hide().attr("src",b.posterImage).on("load",function(){$(this).fadeIn()});d.find(".search-overlay-result-title").html(b.title);
d.find(".search-overlay-result-year").html(b.year);d.attr("title",b.title);d.on("mousemove",function(){app.nav.paused()||app.nav.selectElement($(this))}).on("mouseout",function(){app.nav.paused()||app.nav.deselect()}).on("click",function(){$("#search-overlay-keywords").val($(this).find(".search-overlay-result-title").html());$("#search-overlay-form").submit()});g.append(d.show())})}})}}},200)).on("keydown",function(d){if(27===d.keyCode)b();else if(40===d.keyCode||38===d.keyCode){var e=$("#search-overlay-results").find(".search-overlay-result");
0!==e.length&&(0===e.filter(".selected").length?app.nav.selectElement($(e.get(0))):(40===d.keyCode&&app.nav.down(),38===d.keyCode&&app.nav.up()),d=e.filter(".selected"),$("#search-overlay-keywords").val(d.find(".search-overlay-result-title").html()))}});$("#search-bar").on("submit",function(b){b&&b.preventDefault&&b.preventDefault();b={};var e=$("#keywords").blur().val();"string"===typeof e&&(b.keywords=e);var g=$("#search-sort").find(":selected"),l=g.data("sort");"string"===typeof l&&(b.sort=l);
g=g.data("sort-order");"string"===typeof g&&(b.sortOrder=g);g=$("#search-genre").find(":selected");l=g.data("movie-genre");"string"===typeof l&&(b.genre=l);app.media.movie.list({container:$("#movie-search-results"),filter:b});delete b.genre;l=g.data("tv-genre");"string"===typeof l&&(b.genre=l);app.media.tvShow.list({container:$("#tv-search-results"),filter:b});ga("send","pageview","/index.html?q="+e);return!1});$("#search-genre").on("change",function(){$("#search-bar").submit()});$("#search-sort").on("change",
function(){$("#search-bar").submit()})};e.settings=function(){for(var b=$("[data-storage-id]"),d={"settings-max-download-speed":function(b){b=parseInt(b,10);isNaN(b)||0>b?$("#max-download-speed").val("0").trigger("change"):app.btapp.live("settings",function(d){d&&d.save({max_dl_rate:b})})},"settings-max-upload-speed":function(b){b=parseInt(b,10);isNaN(b)||0>b?$("#max-upload-speed").val("0").trigger("change"):app.btapp.live("settings",function(d){d&&d.save({max_ul_rate:b})})},"settings-keyboard-shortcuts":function(b){e.keyboardShortcuts()}},
g=function(){for(var e=0;e<b.length;e++){var h=$(b.get(e)),g="checkbox"===h.attr("type")?h.is(":checked"):h.val();$.jStorage.set(h.attr("data-storage-id"),g);if(d.hasOwnProperty(h.attr("data-storage-id")))d[h.attr("data-storage-id")](g)}},p=0;p<b.length;p++){var l=$(b.get(p));"checkbox"===l.attr("type")&&(l.val=function(b){var d=$(this);if("undefined"===typeof b)return d.is(":checked");d.attr("checked",b);return d});if(null!==$.jStorage.get(l.attr("data-storage-id")))l.val($.jStorage.get(l.attr("data-storage-id"))).on("change",
g);else $.jStorage.set(l.attr("data-storage-id"),l.val())}$("#settings").submit(function(d){d.preventDefault();for(d=0;d<b.length;d++)$(b.get(d)).trigger("change");return!1});$("#settings-reset").on("click",function(){if(confirm("Warning: Are you sure you want to reset all settings?")){for(var d=0;d<b.length;d++){var e=$(b.get(d));null!==$.jStorage.get(e.attr("data-storage-id"))&&$.jStorage.deleteKey(e.attr("data-storage-id"))}window.location.reload()}});$("#default-download-directory").on("focus",
function(){app.btapp.browseforfolder&&app.btapp.browseforfolder(function(b){"string"===typeof b&&$("#default-download-directory").val(b).trigger("change")})})};e.sidebar=function(){$("#sidebar").find("a").not(".sidebar-foot-link").not("#sidebar-search").on("click",function(b){b&&b.preventDefault&&b.preventDefault();g($(this));return!1});$("#sidebar-bookmarks").on("click",function(){app.nav.switchView("bookmarks");$("#bookmarks").fadeIn();app.lists.renderList("bookmarks",{movie:$("#movie-bookmarks-results"),
tvShow:$("#tv-bookmarks-results")},{movie:"You haven't added any movies to your bookmarks yet.",tvShow:"You haven't added any TV shows to your bookmarks yet."})});$("#sidebar-history").on("click",function(){app.nav.switchView("history");$("#history").fadeIn();app.lists.renderList("history",{movie:$("#movie-history-results"),tvShow:$("#tv-history-results")},{movie:"You haven't watched any movies yet.",tvShow:"You haven't watched any TV shows yet."})});$("#sidebar-search").on("click",function(){$("#search-results").is(":visible")?
$("#keywords").focus():($("#search-overlay-container").animate({width:"400px"}),$("#search-overlay").data("previous-view",app.nav.currentView()).fadeIn(400,function(){$("#search-overlay-keywords").val("").focus()}),app.nav.switchView("search-overlay"))});$("#sidebar-movies").on("click",function(){app.nav.switchView("results");$("#results").fadeIn();app.media.movie.list()});$("#sidebar-tv-shows").on("click",function(){app.nav.switchView("results");$("#results").fadeIn();app.media.tvShow.list()});$("#sidebar-downloads").on("click",
function(){app.nav.switchView("downloads");app.torrents.renderList($("#torrent-list"));$("#downloads").fadeIn().data("update-interval",setInterval(function(){app.torrents.renderList($("#torrent-list"))},1E3))});$("#open-settings").on("click",function(){fn.openModal("#settings-modal")});$("#open-info").on("click",function(){fn.openModal("#info-modal")});$("#open-keyboard-shortcuts").on("click",function(){fn.openModal("#keyboard-shortcuts-modal")});$("#sidebar-donate").click(function(b){b&&b.preventDefault&&
b.preventDefault();b&&b.stopPropagation&&b.stopPropagation();$("#sidebar-donate-popover").fadeIn();$("body").add("#sidebar-donate-popover-close").click(function n(b){$("#sidebar-donate-popover").fadeOut();$("body").unbind("click",n)});return!1});$("#sidebar-donate-popover").click(function(b){b&&b.stopPropagation&&b.stopPropagation()})};e.torqueConnectBtn=function(){$("#setup-torque").on("click",function(){fn.connectToTorque()});$(document).bind("close.facebox",function(){$("#facebox, #facebox_overlay").hide()})};
e.torqueMessageReciever=function(){var b={"plugin:plugin_installed":"plugin installed","plugin:plugin_running":"plugin running","plugin:client_installed":"client installed","plugin:client_running":"client running","client:connected":"client connecting","client:disconnected":"client disconnected",sync:"client connected","client:error":"error","input:creating_torrent":"creating torrent","input:torrent_created":"torrent created","input:redirecting":"redirecting","input:waiting_for_folder_selection":"waiting for selection",
"input:no_files_selected":"no files selected"};app.btapp.on("all",function(d){b.hasOwnProperty(d)&&(app.status=b[d],"client installed"===app.status&&(app.installed=!0),"client connected"===app.status&&(app.connected=!0),"client disconnected"===app.status&&(app.connected=!1),"sync"!==d&&console.log(d))})};e.userTorrent=function(){$("#add-torrent-start").on("click",function(){$("#add-torrent-form").submit()});$("#add-torrent-form").on("submit",function(b){b.preventDefault();b=$("#add-torrent-link").val();
""!==b&&app.torrents.play(b);return!1})};e.views=function(){var b=$("#sidebar");new app.nav.View("bookmarks",[b,$("#movie-bookmarks-results"),$("#tv-bookmarks-results")]);new app.nav.View("history",[b,$("#movie-history-results"),$("#tv-history-results")]);new app.nav.View("search-overlay",[b,$("#search-overlay-results")]);new app.nav.View("search",[b,$("#movie-search-results"),$("#tv-search-results")]);new app.nav.View("results",[b,$("#results")]);new app.nav.View("downloads",[b],0);new app.nav.View("movie-details",
[b,$("#movie-details")]);new app.nav.View("tv-details",[b,$("#tv-details-seasons"),$("#tv-details-episodes"),$("#tv-details-episode")]);new app.nav.View("tv-torrents",[$("#tv-show-torrent-links")],0);new app.nav.View("file-list",[$("#file-select-list")],0);$(".navigable-item").on("mousemove",function(){app.nav.paused()||app.nav.selectElement($(this))}).on("mouseout",function(){app.nav.paused()||app.nav.deselect()})};e.window=function(){$(window).on("beforeunload",function(){if(app.connected){var b=
$("#keep-downloaded-files").is(":checked");app.btapp.get("torrent").each(function(d){d.stop();b||d.remove(Btapp.TORRENT.REMOVE.DELETE_TORRENT_AND_DATA)})}}).on("resize",_.throttle(function(){var b=$("#results");b.outerWidth()/b.outerHeight()>1280/720?$("#movie-details-backdrop, #tv-details-backdrop").find("img").width("100%").height("auto"):$("#movie-details-backdrop, #tv-details-backdrop").find("img").height("100%").width("auto")},500)).resize()}})(window.app);
$(document).ready(function(){app.setup.settings();app.setup.errorTracking();app.setup.keyboardShortcuts();app.setup.loadNewPage();app.setup.modals();app.setup.search();app.setup.sidebar();app.setup.torqueConnectBtn();app.setup.userTorrent();app.setup.views();app.setup.window();$("#sidebar-movies").click();app.player.projekktor=projekktor("#projekktor-player");app.player.videojs=videojs("videojs-player");1==$("#first-run").val()?$("#setup-modal, #modal-bg").fadeIn():fn.connectToTorque()});
(function(e){e.torrents||(e.torrents={});e=e.torrents;var g={},b=["avi","mp4","mkv"],d=function(a){this.hash=a.hash;this.url=a.url;this._btapp=a._btapp||app.btapp.get("torrent").get(this.hash);var c=this._btapp.get("properties");this.name=c.get("name");this.size=c.get("size");this.progress=0<this.size?Math.round(1E3*c.get("downloaded")/this.size)/10:0;this.downloadSpeed=c.get("download_speed");this.metadataResolved=c.get("metadata_resolved");if(a.files)this.files=a.files;else{var d=this.files=[];
this._btapp.get("file").each(function(a){var c=a.get("properties"),e=c.get("name"),e=e.substr(e.lastIndexOf(".")+1).toLowerCase();c.get("is_streamable")&&-1!==b.indexOf(e)?d.push(new n({name:c.get("name"),size:c.get("size"),downloaded:c.get("downloaded"),streaming_url:c.get("streaming_url"),torrent:a.get("torrent"),_btapp:a})):c.save({priority:Btapp.TORRENT.FILE.PRIORITY.NO_DOWNLOAD})})}},n=function(a){this.name=a.name;this.size=a.size;this.downloaded=a.downloaded;this.streaming_url=a.streaming_url;
this.torrent=a.torrent;this._btapp=a._btapp},p=function(a){return null!==a.match(/magnet:\?xt=urn:[a-z0-9]+:[a-z0-9]{32,40}/i)},l=function(a){return null!==a.match(/^[a-z0-9]{32,40}$/i)},f=function(a){var c={};a=a.split("magnet:?")[1];if(!a||0===a.length)return c;a.split("&").forEach(function(a){var b=a.split("=");2===b.length&&(a=b[0],b=b[1],"dn"===a&&(b=decodeURIComponent(b).replace(/\+/g," ")),"tr"===a&&(b=decodeURIComponent(b)),"kt"===a&&(b=decodeURIComponent(b).split("+")),c[a]?Array.isArray(c[a])?
c[a].push(b):c[a]=[c[a],b]:c[a]=b)});var b;c.xt&&(b=c.xt.match(/^urn:btih:(.{40})/))?c.infoHash=b[1]:c.xt&&(b=c.xt.match(/^urn:btih:(.{32})/))&&(c.infoHash=b[1]);c.dn&&(c.name=c.dn);c.kt&&(c.keywords=c.kt);"string"===typeof c.tr?c.announce=[c.tr]:Array.isArray(c.tr)&&(c.announce=c.tr);return c},h=e.add=function(a,c){app.connected?(console.log("torrents: adding: ",a),l(a)&&(a="magnet:?xt=urn:btih:"+a),app.btapp.get("add").torrent({url:a,location:$("#default-download-directory").val(),callback:function(b){app.btapp.live("torrent * properties",
function r(b,e){app.btapp.unbind("torrent * properties",r);if(p(a)){if(b.get("hash").toLowerCase()!==f(a).infoHash.toLowerCase())return}else if(b.get("uri").toLowerCase()!==a.toLowerCase()&&b.get("download_url").toLowerCase()!==a.toLowerCase())return;var h=b.get("hash");console.log("torrents: added: ",h);g[h]=new d({hash:h,url:a,_btapp:e});c&&c(h)})}})):fn.connectToTorque()},k=e.get=function(a){return"*"===a?g:g[a]},s=e.start=function(a){var c=k(a)._btapp;c.start();c.unpause();c.set_priority(Btapp.TORRENT.PRIORITY.MEDIUM);
_.each(k(a).files,function(a){a._btapp.get("properties").save({priority:Btapp.TORRENT.FILE.PRIORITY.MEDIUM})});c.get("properties").unbind("change",w).on("change",w)},c=e.stop=function(a){a=k(a)._btapp;a.stop();a.get("properties").unbind("change",w)},a=e.remove=function(a){"undefined"!==typeof k(a)&&("undefined"!==typeof k(a)._btapp&&k(a)._btapp.remove(Btapp.REMOVE.DELETE_BOTH),delete g[a])},y=e.play=_.throttle(function(b,d,e){if(l(b)||"torrent"===b.split("?")[0].split("#")[0].split(".").pop()||p(b))if("undefined"===
typeof k(b))h(b,function(a){y(a,d,e)});else{s(b);var f=$("#download-stats").hide();if(k(b).metadataResolved){fn.status("Connected");var r=k(b).files;if("undefined"!==typeof e&&r[e]instanceof n){_.each(g,function(a){b!==a.hash&&c(a.hash)});1!==r.length&&_.each(r,function(a,c){c===e?a._btapp.get("properties").save({priority:Btapp.TORRENT.FILE.PRIORITY.MEDIUM}):a._btapp.get("properties").save({priority:Btapp.TORRENT.FILE.PRIORITY.NO_DOWNLOAD})});var z=function(){r=k(b).files;var a=100*r[e].downloaded/
r[e].size;100<=a||"undefined"===typeof k(b)?(k(b)._btapp.get("properties").unbind("change"),f.hide(),c(b),(a=$("#player").data("next-hash"))&&(l(a)&&"undefined"!==typeof k(a)?C(a):h(a,C))):(v(r[e].name,a,k(b).downloadSpeed,!1),f.show())},C=function(b){console.log("preloading next:",b);s(b);var d=function(){v(k(b).name,k(b).progress,k(b).downloadSpeed,!0);f.show()};k(b)._btapp.get("properties").unbind("change",d).on("change",d);var d=$("#player"),e=d.data("on-close");d.data("next-hash",null);d.data("on-close",
function(){c(b);$("#keep-downloaded-files").is(":checked")||a(b);e&&e()})};k(b)._btapp.get("properties").unbind("change",z).on("change",z);var A=0,u=[],B=_.throttle(function(){u.push(k(b).downloadSpeed);10<u.length&&(u=u.slice(u.length-10));var a=_.reduce(u,function(a,c){return a+c},0)/u.length;A=Math.max(A,D(a,r[e].size,r[e].downloaded));100>=A?(fn.status("Buffering...",A+"%"),B()):(fn.status("Buffering...","100%"),fn.status(!1),E(r[e],d))},500);B()}else t(r,function(c,e){-1===e?(a(b),fn.status(!1),
fn.openModal("#no-files-warning-modal")):y(b,d,e)})}else y(b,d,e),fn.status("Connecting...")}else console.log("torrents: play: invalid hash: ",b)},500),t=function(a,c){if(1===a.length)c(a[0],0);else if(0>=a.length)c(null,-1);else{var b=$("#file-select-list").empty();_.each(a,function(d,e){var f=d.name,h=Math.round(100*d.size/1048576)/100,g=$("<div class='link navigable-item' title='"+f+"'>"+(e+1)+". "+f+"</div>"),f=$("<span class='link-info'>"+h+" MB</span>");g.on("click",function(){c(a[e],e)}).on("mousemove",
function(){app.nav.paused()||app.nav.selectElement(g)}).on("mouseout",function(){app.nav.paused()||app.nav.deselect()});b.append(g.append(f))});fn.status(!1);fn.openModal("#file-list-modal");app.nav.switchView("file-list")}},D=function(a,c,b){var d=100*b/c;return Math.max(Math.round(27E5/(c===b?0:(c-b)/a))/10,Math.round(1E3*d/app.maxBufferPercentage)/10)},v=function(a,c,b,d){b=Math.round(10*b/1024)/10;var e=$(".download-stats");e.removeClass("low med high");5.12<b&&(204.8>b?e.addClass("low"):768>
b?e.addClass("med"):e.addClass("high"));e.each(function(){var e=$(this);e.find(".download-stats-filename").html(a).attr("title",a);d?e.find(".download-stats-preloading").show():e.find(".download-stats-preloading").hide();e.find(".download-stats-progress").find(".bar").css("width",c+"%").siblings(".percentage").html(Math.round(10*c)/10+"%");e.find(".download-stats-speed").html(b+" KB/s");e=e.find(".download-stats-speed-chart");e.append("<div class='bar' data-speed='"+b+"'></div>");var f=_.reduce(e.children(),
function(a,c){return Math.max($(c).attr("data-speed"),a)},1);e.children().each(function(){$(this).height(100*$(this).attr("data-speed")/f+"%")});50<e.children().length&&e.children().first().remove()});e.show()},E=function(b,d){var e=d?d.metadata.title:b.name,f=b.name.substr(b.name.lastIndexOf(".")+1).toLowerCase();if(-1!==["mkv","mp4","avi"].indexOf(f)){var g=b.streaming_url;console.log("playing media: "+f+" file from "+g);$("#file-list-modal").is(":visible")&&($("#file-list-modal, .modal, #modal-bg, #status").hide(),
$("#modal-bg").attr("data-modal",""));app.player.projekktor.setStop&&app.player.projekktor.setStop();app.player.videojs.pause&&app.player.videojs.pause();$(".player").hide();fn.openModal("#player");var h=$("#player");h.data("on-close",function(){app.player.projekktor.setStop&&app.player.projekktor.setStop();app.player.videojs.pause&&app.player.videojs.pause();c(b.torrent);$("#keep-downloaded-files").is(":checked")||a(b.torrent);h.data("next-hash",null);h.data("on-close",null)});d&&app.lists.addToList("history",
d.mediaType,d);var k=$("<div id='player-overlay' style='display: none'></div>").append("<div class='overlay-title' title='"+e+"'><a onclick='$(\"#modal-bg\").click()' style='padding-right: 20px'><i class='icon-chevron-left'></i></a>"+e+"</div>").append($("#download-stats").clone().attr("id","")),e=function(){c(b.torrent);$("#keep-downloaded-files").is(":checked")||a(b.torrent);var d=$("#player"),e=d.data("on-ended");e&&e();d.data("on-ended",null)};if("avi"===f){for(var f=!1,l=0;l<navigator.plugins.length;l++)if(-1!=
navigator.plugins[l].name.indexOf("VLC")){f=!0;break}if(f){$("#player").attr("class","modal modal-full projekktor");$("#video-overlay").remove();var n,f=function(){clearTimeout(n);k.is(":hidden")&&k.fadeIn();n=setTimeout(function(){k.fadeOut()},2500)};$("#projekktor-player").append(k);$("#projekktor-container").unbind("mousemove",f).on("mousemove",f);app.player.projekktor.removeListener("done",e);app.player.projekktor.addListener("done",e);app.player.projekktor.setFile(g,"video/x-msvideo");app.player.projekktor.setPlay()}else console.log("VLC Web Player is not yet installed"),
fn.openModal("#vlc-install-modal")}else $("#player").attr("class","modal modal-full videojs"),app.player.videojs.controls(!1),app.player.videojs.on("loadeddata",function(){app.player.videojs.controls(!0)}),app.player.videojs.off("ended").on("ended",e),app.player.videojs.on("error",function(){$(".vjs-error-retry").remove();var a=$("<a class='vjs-error-retry'><i class='icon-repeat'></i></a>");a.on("click",function(){app.player.videojs.src(g).play()});$(".vjs-error-display").append(a)}),app.player.videojs.overlay({content:k.fadeIn()}),
app.player.videojs.src(g).play()}},x=e.updateAll=_.throttle(function(){app.connected&&app.btapp.live("torrent * properties",w)},5E3),w=function(a){app.connected&&"undefined"!==typeof app.btapp.get("torrent").get(a.get("hash"))&&(g[a.get("hash")]=new d({hash:a.get("hash"),url:a.get("uri")}))};e.renderList=function(b){b=b||$("<table></table>");x();var d=_.map(g,function(a){return _.pick(a,"hash","downloadSpeed","progress")});if(_.isEqual(b.data("torrent-data"),d))return b;b.data("torrent-data",d);b.empty();
if(0===_.size(g))return b.append("<tr style='border: none'><td class='no-results' style='padding: 20px'>No files...</td></tr>"),b;var e=$("<tbody></tbody>"),f=$("#torrent-list-row-template");b.append("<thead><tr><th>Name</th><th>Size</th><th>Speed</th><th>Progress</th><th></th></tr></thead>");b.data("torrents",g);_.each(g,function(b){var d=f.clone();d.find(".torrent-list-name").attr("title",b.name.replace(/['"]/g,"")).html(b.name);var g=d.find(".torrent-list-progress");g.find(".bar").width(b.progress+
"%");g.find(".percentage").html(b.progress+"%");d.find(".torrent-list-speed").find("span").html(Math.round(10*b.downloadSpeed/1024)/10+" KB/s");d.find(".torrent-list-size").find("span").html(Math.round(b.size/1073741824*100)/100+" GB");d.find(".torrent-list-name").on("click",function(){y(b.hash)});0<b.downloadSpeed?(d.find(".torrent-list-start").hide(),d.find(".torrent-list-stop").show().on("click",function(){$(this).is(".disabled")||($(this).find(".icon-pause").removeClass("icon-pause").addClass("icon-spinner"),
c(b.hash))})):(d.find(".torrent-list-stop").hide(),d.find(".torrent-list-start").show().on("click",function(){$(this).is(".disabled")||($(this).find(".icon-download-circle").removeClass("icon-download-circle").addClass("icon-spinner"),s(b.hash))}));100<=b.progress&&d.find(".torrent-list-start, .torrent-list-stop").addClass("disabled");d.find(".torrent-list-open-containing").on("click",function(){k(b.hash)._btapp.open_containing()});d.find(".torrent-list-remove").on("click",function(){a(b.hash)});
e.append(d)});return b.append(e)}})(window.app);
